#!/usr/bin/env node
/**
 * Standalone installer for the AtlasDeck ↔ OpenClaw calendar integration.
 *
 * Usage:
 *   npm run setup:calendar             # runs install
 *   npm run setup:calendar -- --status # just prints status
 *
 * Environment variables (all optional):
 *   OPENCLAW_DIR              defaults to /root/.openclaw
 *   ATLASDECK_BASE_URL        defaults to http://localhost:3000
 *   OPENCLAW_SERVICE_TOKEN    if set, used as-is; otherwise read from openclaw.json
 *                             or generated and written to .env.local
 *
 * Designed for 1-click VPS install: run after `npm install` and before / after
 * starting the AtlasDeck server.
 */

import { getInstallStatus, runInstall } from "../src/lib/calendar-installer";
import type { InstallReport } from "../src/lib/calendar-installer";

const COLORS = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  gray: "\x1b[90m",
};

function color(c: keyof typeof COLORS, s: string): string {
  if (!process.stdout.isTTY) return s;
  return `${COLORS[c]}${s}${COLORS.reset}`;
}

function statusBadge(status: string): string {
  switch (status) {
    case "ok":
      return color("green", "✓");
    case "missing":
      return color("yellow", "○");
    case "error":
      return color("red", "✗");
    case "skipped":
      return color("gray", "·");
    default:
      return "?";
  }
}

function printReport(report: InstallReport): void {
  console.log("");
  console.log(color("bold", "AtlasDeck × OpenClaw — Calendar integration"));
  console.log(color("dim", `OPENCLAW_DIR: ${report.openclaw_dir}`));
  console.log(color("dim", `BASE_URL:     ${report.base_url}`));
  console.log("");

  for (const step of report.steps) {
    console.log(`  ${statusBadge(step.status)} ${color("bold", step.label)}`);
    if (step.detail) console.log(color("gray", `      ${step.detail}`));
  }

  console.log("");
  if (report.ready) {
    console.log(color("green", "✓ Tudo pronto."));
  } else {
    const failing = report.steps.filter((s) => s.status !== "ok").length;
    console.log(color("yellow", `⚠ ${failing} passo${failing > 1 ? "s" : ""} pendente${failing > 1 ? "s" : ""}.`));
  }
  console.log("");
}

function main(): void {
  const args = process.argv.slice(2);
  const statusOnly = args.includes("--status") || args.includes("-s");
  const help = args.includes("--help") || args.includes("-h");

  if (help) {
    console.log(`Usage: npm run setup:calendar [-- --status]

Without flags: installs (idempotent). With --status: prints current state only.

Environment:
  OPENCLAW_DIR             default /root/.openclaw
  ATLASDECK_BASE_URL       default http://localhost:3000
  OPENCLAW_SERVICE_TOKEN   optional — autogenerated if missing
`);
    return;
  }

  try {
    const report = statusOnly ? getInstallStatus() : runInstall();
    printReport(report);
    process.exit(report.ready ? 0 : 1);
  } catch (err) {
    console.error(color("red", "Installation failed:"), err);
    process.exit(2);
  }
}

main();
